server:
  port: 9000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 启用通过服务名自动转发
          lower-case-service-id: true
      routes:
        - id: config-service
          uri: lb://config-service
          predicates:
            - Path=/config/**
          filters:
            - StripPrefix=1  # 去掉 /config 前缀
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**    # 拦截 /user-service 相关请求 然后使用user-service服务去处理
          filters:
            - StripPrefix=1            # 去掉 /user-service 前缀

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
