spring:
  application:
    name: user-service # 你的服务名称
  profiles:
    active: dev        # 激活的 profile

  config:
    import: optional:configserver:http://localhost:8888  # （推荐）

# 如果 user-service 还需要注册到 Eureka (推荐)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka Server 的地址
    register-with-eureka: true # 将 user-service 注册到 Eureka
    fetch-registry: true     # 从 Eureka 获取服务列表          # Git 分支（如果你用 Git 存配置），可以是 main 或 master 等
