spring:
  application:
    name: user-service  # 对应 config-server 中的配置文件名称，比如 user-service.yml 或 user-service-dev.yml

  config:
    import: "configserver:"  # 注意用引号，否则可能会触发 YAML 的语法错误

  cloud:
    config:
      uri: http://localhost:8888  # 你的 config-server 地址
      profile: dev               # 对应远程配置文件中的环境，如 user-service-dev.yml
      label: main                # Git 分支（如果你用 Git 存配置），可以是 main 或 master 等
